# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb',
            name='grade',
        ),
        migrations.AddField(
            model_name='climb',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='climb',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
