# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160611_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('RP', 'Redpoint'), ('F', 'Flash'), ('OS', 'Onsight')], max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('climb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Climb')),
                ('grade', models.CharField(choices=[('V0', 'V0'), ('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10'), ('V11', 'V11'), ('V12', 'V12'), ('V13', 'V13'), ('V14', 'V14'), ('V15', 'V15'), ('V16', 'V16')], max_length=50)),
            ],
            bases=('main.climb',),
        ),
        migrations.CreateModel(
            name='SportRoute',
            fields=[
                ('climb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Climb')),
                ('grade', models.CharField(choices=[('5.8', '5.9'), ('5.9', '5.8'), ('5.10a', '5.10a'), ('5.10b', '5.10b'), ('5.10c', '5.10c'), ('5.10d', '5.10d'), ('5.11a', '5.11a'), ('5.11b', '5.11b'), ('5.11c', '5.11c'), ('5.11d', '5.11d'), ('5.12a', '5.12a'), ('5.12b', '5.12b'), ('5.12c', '5.12c'), ('5.12d', '5.12d'), ('5.13a', '5.13a'), ('5.13a', '5.13b'), ('5.13a', '5.13c'), ('5.13a', '5.13d'), ('5.14a', '5.14a'), ('5.14b', '5.14b'), ('5.14c', '5.14c'), ('5.14d', '5.14d'), ('5.15a', '5.15a'), ('5.15b', '5.15b'), ('5.15c', '5.15c')], max_length=50)),
            ],
            bases=('main.climb',),
        ),
        migrations.CreateModel(
            name='BoulderAscent',
            fields=[
                ('ascent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Ascent')),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Boulder')),
            ],
            bases=('main.ascent',),
        ),
        migrations.CreateModel(
            name='SportAscent',
            fields=[
                ('ascent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Ascent')),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SportRoute')),
            ],
            bases=('main.ascent',),
        ),
    ]
