# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ascent_boulder_boulderascent_sportascent_sportroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('boulder_ascents', models.ManyToManyField(to='main.BoulderAscent')),
                ('sport_ascents', models.ManyToManyField(to='main.SportAscent')),
            ],
        ),
    ]
